// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOmPm3kPsS2dePqNH_gavHxfqIIitJJhc',
    appId: '1:245224518875:web:8ef660f8fa10788e5ec8fe',
    messagingSenderId: '245224518875',
    projectId: 'care-companion-app',
    authDomain: 'care-companion-app.firebaseapp.com',
    storageBucket: 'care-companion-app.appspot.com',
    measurementId: 'G-ECEMP1JBDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8TitMwQY277DMxcZhHTUc3Rs1S7LLfA8',
    appId: '1:245224518875:android:2588ae971fdb13585ec8fe',
    messagingSenderId: '245224518875',
    projectId: 'care-companion-app',
    storageBucket: 'care-companion-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsPD86T3E4LxSwQmM9UuoTwTRDnzRhYDc',
    appId: '1:245224518875:ios:2e0a493fff3311ea5ec8fe',
    messagingSenderId: '245224518875',
    projectId: 'care-companion-app',
    storageBucket: 'care-companion-app.appspot.com',
    iosClientId:
        '245224518875-m3eanbk4bsh7gfddip3da4a32h2bb9p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.careCompanionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsPD86T3E4LxSwQmM9UuoTwTRDnzRhYDc',
    appId: '1:245224518875:ios:2e0a493fff3311ea5ec8fe',
    messagingSenderId: '245224518875',
    projectId: 'care-companion-app',
    storageBucket: 'care-companion-app.appspot.com',
    iosClientId:
        '245224518875-m3eanbk4bsh7gfddip3da4a32h2bb9p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.careCompanionApp',
  );
}
